title: "Pedro H. P. Rocha"
description: "Ph.D. Candidate in Media & Communication"
email: "pedrocha.edu"
url: "https://pedrocha.github.io"
baseurl: ""

author:
  name: Pedro H. P. Rocha
  affiliation: "College of Media & Communication, Texas Tech University"

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
