title: "Pedro H. P. Rocha"
description: "Doctoral Candidate and Fulbright Fellow"
email: "pedrocha@ttu.edu"
url: "https://pedrocha.com"
baseurl: ""

author:
  name: Pedro H. P. Rocha
  affiliation: "College of Media & Communication, Texas Tech University"

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

scholar: "https://scholar.google.com/citations?user=LBnOt9wAAAAJ&hl=en&inst=6726858233868544323"
linkedin: "https://www.linkedin.com/in/pedrohprocha/"
orcid: "https://orcid.org/0000-0002-2762-9891"
bluesky: "https://bsky.app/profile/pedrohprocha.bsky.social"
lattes: "http://lattes.cnpq.br/8720377365114820"
researchgate: "https://www.researchgate.net/profile/Pedro-Rocha-84?ev=hdr_xprf"
